[build]
  functions = "netlify/functions"
  publish = "static"

[[redirects]]
  from = "/static/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/ws"
  to = "/.netlify/functions/websocket"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["static/**/*"]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 8888
  publish = "static"
  autoLaunch = true