[build]
  command = """
    tsc && \
    cp -r static lib && \
    cp -r package.json lib && \
    cd lib && \
    touch yarn.lock && \
    yarn
  """
  publish = "lib"

[build.environment]
  NODE_VERSION = "18"

# Production process type
[build.processing]
  skip_processing = true

# Configure the web process
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add process management
[build.lifecycle]
  onBuild = "pm2 start lib/index.js --name app"

# Port configuration
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "http://localhost:3000/:splat"