[build]
  functions = "netlify/functions"
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions."websocket"]
  included_files = []

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 8888
  publish = "static"
  autoLaunch = true