[build]
  command = """
    tsc && \
    cp -r static lib && \
    cd lib && \
    touch yarn.lock && \
    cp -r package.json lib && \
    yarn && \
    node index.js
  """
  publish = "lib"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm run dev" # or your development command
  port = 3000
  publish = "lib"
  targetPort = 3000
  framework = "#custom"